name: Kwiki-IndexedSearch
version: 29
abstract: Kwiki Plugin to search a kwiki
author: Russell Heilling <chewtoy@s8n.net
license: perl
distribution_type: module
requires:
  perl: 5.6.0
  Kwiki: 0.32
  Kwiki::Search: 0.11
  Kwiki::Indexer: 2
  YAML: 0.35
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
